# Generated by Django 5.1.15 on 2026-10-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_id', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('pickup_address', models.CharField(max_length=255)),
                ('pickup_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('drop_address', models.CharField(max_length=255)),
                ('drop_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('drop_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('pickup_date', models.DateField()),
                ('pickup_time', models.TimeField()),
                ('passengers', models.PositiveIntegerField(default=1)),
                ('distance_km', models.DecimalField(decimal_places=2, help_text='Road distance in kilometers', max_digits=8)),
                ('duration_mins', models.PositiveIntegerField(default=15, help_text='Estimated road duration in minutes')),
                ('base_fare', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('distance_fare', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('waiting_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('night_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('additional_passenger_charge', models.DecimalField(decimal_places=2, default=0.0, max_digits=8)),
                ('total_fare', models.DecimalField(decimal_places=2, max_digits=8)),
                ('payment_method', models.CharField(choices=[('cash', 'Cash on Ride'), ('upi', 'UPI Payment')], default='cash', max_length=20)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('driver_assigned', 'Driver Assigned'), ('driver_arriving', 'Driver Arriving'), ('trip_started', 'Trip Started'), ('trip_completed', 'Trip Completed'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('cancellation_reason', models.TextField(blank=True, null=True)),
                ('customer_notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
