# Generated by Django 5.1.15 on 2026-10-02 08:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DriverBookingRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending Admin Approval'), ('approved', 'Approved / Assigned'), ('rejected', 'Rejected'), ('cancelled', 'Cancelled')], db_index=True, default='pending', max_length=20)),
                ('driver_note', models.TextField(blank=True, help_text='Optional note from driver', null=True)),
                ('admin_notes', models.TextField(blank=True, help_text='Notes from admin upon review', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_requests', to='bookings.booking')),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_requests', to='drivers.driver')),
            ],
            options={
                'ordering': ['-created_at'],
                'unique_together': {('booking', 'driver')},
            },
        ),
    ]
