# Generated by Django 5.1.15 on 2026-10-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='billable_km',
            field=models.DecimalField(decimal_places=2, default=130.0, help_text='Billed distance with 130 KM minimum', max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='driver_bata',
            field=models.DecimalField(decimal_places=2, default=400.0, help_text='Driver Bata charge', max_digits=8),
        ),
        migrations.AlterField(
            model_name='booking',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=8),
        ),
    ]
