# Generated by Django 5.1.15 on 2026-10-02 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FareSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('Mini', 'Mini'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Premium', 'Premium')], max_length=20, unique=True)),
                ('base_fare', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('min_fare', models.DecimalField(decimal_places=2, default=80.0, max_digits=8)),
                ('waiting_charge_per_min', models.DecimalField(decimal_places=2, default=2.0, max_digits=6)),
                ('night_charge_percent', models.DecimalField(decimal_places=2, default=15.0, help_text='Percentage added for night rides (10 PM - 6 AM)', max_digits=5)),
                ('additional_passenger_charge', models.DecimalField(decimal_places=2, default=20.0, help_text='Charge for extra passengers exceeding standard capacity', max_digits=6)),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Hyundai i20, Toyota Corolla', max_length=100)),
                ('vehicle_type', models.CharField(choices=[('Mini', 'Mini'), ('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Premium', 'Premium')], default='Sedan', max_length=20)),
                ('vehicle_number', models.CharField(help_text='Registration Plate Number', max_length=30, unique=True)),
                ('model', models.CharField(blank=True, help_text='Year/Model e.g. 2023', max_length=50, null=True)),
                ('capacity', models.PositiveIntegerField(default=4)),
                ('base_fare', models.DecimalField(decimal_places=2, default=100.0, max_digits=8)),
                ('price_per_km', models.DecimalField(decimal_places=2, default=15.0, max_digits=8)),
                ('status', models.CharField(choices=[('available', 'Available'), ('maintenance', 'Maintenance'), ('inactive', 'Inactive')], default='available', max_length=20)),
                ('image_url', models.CharField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['vehicle_type', 'name'],
            },
        ),
    ]
