# Generated by Django 5.1.15 on 2026-10-02 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='image',
            field=models.ImageField(blank=True, help_text='Upload vehicle photograph', null=True, upload_to='vehicles/'),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='image_url',
            field=models.CharField(blank=True, help_text='Or external image URL', max_length=500, null=True),
        ),
    ]
