# Generated by Django 5.1.15 on 2026-10-04 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0002_vehicle_image_alter_vehicle_image_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='faresetting',
            name='driver_bata',
            field=models.DecimalField(decimal_places=2, default=400.0, help_text='Driver Bata charge (e.g. Rs.400)', max_digits=6),
        ),
        migrations.AddField(
            model_name='faresetting',
            name='min_km',
            field=models.DecimalField(decimal_places=2, default=130.0, help_text='Minimum base distance (e.g. 130 KM)', max_digits=6),
        ),
        migrations.AlterField(
            model_name='faresetting',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='faresetting',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Innova Crysta', 'Innova Crysta')], max_length=30, unique=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='model',
            field=models.CharField(blank=True, help_text='Year/Model e.g. 2024', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='name',
            field=models.CharField(help_text='e.g. Maruti Dzire, Toyota Innova Crysta', max_length=100),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_km',
            field=models.DecimalField(decimal_places=2, default=14.0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.CharField(choices=[('Sedan', 'Sedan'), ('SUV', 'SUV'), ('Innova Crysta', 'Innova Crysta')], default='Sedan', max_length=30),
        ),
    ]
