# Generated by Django 5.1.15 on 2026-10-02 08:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drivers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='car_image',
            field=models.ImageField(blank=True, null=True, upload_to='driver_cars/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='car_photo',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='driver',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='drivers/'),
        ),
        migrations.AddField(
            model_name='driver',
            name='vehicle_number',
            field=models.CharField(blank=True, help_text='Vehicle plate number e.g. KA-05-AB-1234', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='email',
            field=models.EmailField(blank=True, help_text='Driver email address (Optional)', max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='driver',
            name='phone',
            field=models.CharField(help_text='Driver mobile phone number (Required)', max_length=20),
        ),
    ]
