# Generated by Django 5.1.15 on 2026-10-02 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash on Delivery (COD)'), ('upi', 'UPI Payment'), ('gpay', 'Google Pay (GPay)'), ('card', 'Credit/Debit Card (Future)')], default='cash', max_length=20),
        ),
    ]
