# Generated by Django 5.1.15 on 2026-10-02 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='Official GPay / UPI Scanner', max_length=150)),
                ('upi_id', models.CharField(blank=True, default='jhaztaxi@upi', max_length=100)),
                ('payee_name', models.CharField(blank=True, default='JhazTaxi Travels', max_length=150)),
                ('phone_number', models.CharField(blank=True, default='+91 98765 43210', max_length=20)),
                ('qr_image', models.ImageField(blank=True, null=True, upload_to='payment_qr/')),
                ('instructions', models.TextField(blank=True, default='Scan this official QR code using Google Pay, PhonePe, Paytm, or any BHIM UPI app. Show payment confirmation screen to your driver upon arrival or trip completion.')),
                ('is_active', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Payment Setting',
                'verbose_name_plural': 'Payment Settings',
            },
        ),
    ]
